name: "Build"
on:
  pull_request:
    paths-ignore:
      - '.txt'
      - '*.MD'
      - '*.md'
      - 'LICENSE'
      - 'docs/**'
  push:
    branches:
      - master
      - develop
      - release/*
    tags-ignore:
      - '*'
    paths-ignore:
      - '.txt'
      - '*.MD'
      - '*.md'
      - 'LICENSE'
      - 'docs/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [15]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          architecture: x64
      - name: Cache Maven packages
        uses: actions/cache@v2.1.5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn clean install

      - name: Black Duck Scanner
       # You may pin to the exact commit or the version.
       # uses: philips-labs/blackduck-scanner-action@f8a604ccb9df9a6450b35ac102b30c5b00958d87
        uses: philips-labs/blackduck-scanner-action@v1.3
        with:
             # Blackduck project name
            projectName: Webgoat_github
            # Blackduck project version prefix
            versionPrefix: 1
        # Blackduck url
            url: https://testing.blackduck.synopsys.com/
        # Blackduck token
            token: secrets.BD_TOKEN
        # sourcePath
            sourcePath: /
        # Extra arguments that will be passed to the detector
            extraArgs: /
  notify-slack:
    if: github.event_name == 'push' && (success() || failure())
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: "Slack workflow notification"
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
    
    
  
